os: linux
dist: bionic

language: node_js
node_js:
  - 10

cache: npm

install:
  - npm install -g gatsby

script:
  - npm install && npm run build
  - if [ "$TRAVIS_BRANCH" = "src" ]; then npm run deploy; fi
